export const state = {
    map: null,
    fishingZonesLayer: null,
    socket: null,
    canvasRenderer: null,
    config: {},
    baseLayers: {},
    baseLayerOrder: [],
    currentBaseLayerKey: 'coastline',
    boatsData: {},
    allBoatsInfo: {},
    selectedBoatId: null,
    historyDisplayLayer: L.layerGroup(),
    showLabels: false,
    dailyWarningCount: 0,
    todaysWarnings: [],
    todaysWarningMap: new Map(),
    isHistoryView: false,
    isNotificationCenterOpen: false,
    unseenNotificationCount: 0,
    warningTrend: [],
};
